site_name: neuronovae
site_url: https://readthedocs.org/neuronovae/
repo_name: GitHub
repo_url: https://github.com/darikoneil/neuronovae
site_author: Darik A. O'Neil

nav:
  - Welcome: index.md
  - Installation: installation.md
  - Theory: theory.md
  - Quickstart: quickstart.md
  - Usage:
      - usage/visualization.md
      - usage/FAQ.md
  - Examples:
      - examples/example.md

theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.integrate
  font:
    text: Lexend
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - tags
  - autorefs
  - api-autonav:
        modules: [ neuronovae, ]
        module_options: { }
        nav_section_title: "API Reference"
        api_root_uri: "reference"
        nav_item_prefix: "<code class='doc-symbol doc-symbol-nav doc-symbol-module'></code>"
        exclude_private: false
        show_full_namespace: false
        on_implicit_namespace_package: "warn"
  - mkdocstrings:
      handlers:
        python:
          theme: material
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://matplotlib.org/stable/objects.inv
          options:
            # DOCSTRINGS
            docstring_style: google
            docstring_section_style: list
            # CROSS-REF
            relative_crossrefs: true
            scoped_crossrefs: true
            signature_crossrefs: true
            # MEMBERS
            inherited_members: true
            summary: false
            members_order: alphabetical
#            show_labels: true
            group_by_category: true
            # HEADINGS
            heading_level: 1
            show_category_heading: true
#            show_root_heading: true
#            show_root_full_path: false
            # SIGNATURES
            line_length: 88
#            seperate_signature: false
#            show_signature_annotations: true
#            show_signature_type_parameters: true
#            annotations_path: source
#            show_attribute_values: true
            # MISC
            allow_inspection: true
            backlinks: tree
            show_bases: true
            show_source: false
            extensions:
              - griffe_pydantic:
                  schema: true
              - griffe_inherited_docstrings:
                  merge: true
              - griffe_sphinx
              - griffe_autodocstringstyle

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
